name: Lint on Push Request

on:
  push: 
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      # Python + Pylint
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: install Pytest
        run: pip install pytest
        
      - name: Run Pytest
        run: |
          py_files=$(git ls-files '*.py')
          if [ -n "$py_files" ]; then
            pytest
          else
            echo "No Python files found, skipping pytest."
          fi

      - name: Install pylint
        run: pip install pylint

      - name: Run Pylint
        run: |
          py_files=$(git ls-files '*.py')
          if [ -n "$py_files" ]; then
            pylint $py_files
          else
            echo "No Python files found, skipping pylint."
          fi
